# Generated by Django 4.0.3 on 2022-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_hash",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Уникальный хеш",
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Хэш транзакции создания токена",
                    ),
                ),
                (
                    "media_url",
                    models.CharField(max_length=100, verbose_name="Картинка"),
                ),
                (
                    "owner",
                    models.CharField(
                        max_length=100,
                        verbose_name="адрес пользователя в сети Ethereum",
                    ),
                ),
            ],
        ),
    ]
