# Generated by Django 4.0.3 on 2022-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='Хэш транзакции создания токена'),
        ),
    ]
