# Generated by Django 4.0.3 on 2022-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_token_tx_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="tx_hash",
            field=models.CharField(
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="Хэш транзакции создания токена",
            ),
        ),
    ]
